using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace ResourceParser
{
    public partial class ParserForm
    {
        internal class JobAndLevelPair
        {
            internal String Job;
            internal Byte Level;
            internal JobAndLevelPair()
            {
            }
        }
        private Dictionary<String, JobAndLevelPair> mapJobAbil2Job = new Dictionary<string, JobAndLevelPair>()
        {
            {"Mighty Strikes", new JobAndLevelPair{Job="WAR", Level=1}},
            {"Hundred Fists", new JobAndLevelPair{Job="MNK", Level=1}},
            {"Benediction", new JobAndLevelPair{Job="WHM", Level=1}},
            {"Manafont", new JobAndLevelPair{Job="BLM", Level=1}},
            {"Chainspell", new JobAndLevelPair{Job="RDM", Level=1}},
            {"Perfect Dodge", new JobAndLevelPair{Job="THF", Level=1}},
            {"Invincible", new JobAndLevelPair{Job="PLD", Level=1}},
            {"Blood Weapon", new JobAndLevelPair{Job="DRK", Level=1}},
            {"Familiar", new JobAndLevelPair{Job="BST", Level=1}},
            {"Soul Voice", new JobAndLevelPair{Job="BRD", Level=1}},
            {"Eagle Eye Shot", new JobAndLevelPair{Job="RNG", Level=1}},
            {"Meikyo Shisui", new JobAndLevelPair{Job="SAM", Level=1}},
            {"Mijin Gakure", new JobAndLevelPair{Job="NIN", Level=1}},
            {"Spirit Surge", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Astral Flow", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Berserk", new JobAndLevelPair{Job="WAR", Level=15}},
            {"Warcry", new JobAndLevelPair{Job="WAR", Level=35}},
            {"Defender", new JobAndLevelPair{Job="WAR", Level=25}},
            {"Aggressor", new JobAndLevelPair{Job="WAR", Level=45}},
            {"Provoke", new JobAndLevelPair{Job="WAR", Level=5}},
            {"Focus", new JobAndLevelPair{Job="MNK", Level=25}},
            {"Dodge", new JobAndLevelPair{Job="MNK", Level=15}},
            {"Chakra", new JobAndLevelPair{Job="MNK", Level=35}},
            {"Boost", new JobAndLevelPair{Job="MNK", Level=5}},
            {"Counterstance", new JobAndLevelPair{Job="MNK", Level=45}},
            {"Steal", new JobAndLevelPair{Job="THF", Level=5}},
            {"Flee", new JobAndLevelPair{Job="THF", Level=25}},
            {"Hide", new JobAndLevelPair{Job="THF", Level=45}},
            {"Sneak Attack", new JobAndLevelPair{Job="THF", Level=15}},
            {"Mug", new JobAndLevelPair{Job="THF", Level=35}},
            {"Shield Bash", new JobAndLevelPair{Job="PLD", Level=15}},
            {"Holy Circle", new JobAndLevelPair{Job="PLD", Level=5}},
            {"Sentinel", new JobAndLevelPair{Job="PLD", Level=30}},
            {"Souleater", new JobAndLevelPair{Job="DRK", Level=30}},
            {"Arcane Circle", new JobAndLevelPair{Job="DRK", Level=5}},
            {"Last Resort", new JobAndLevelPair{Job="DRK", Level=15}},
            {"Charm", new JobAndLevelPair{Job="BST", Level=1}},
            {"Gauge", new JobAndLevelPair{Job="BST", Level=10}},
            {"Tame", new JobAndLevelPair{Job="BST", Level=30}},
            {"Pet commands", new JobAndLevelPair{Job="BST", Level=1}},
            {"Scavenge", new JobAndLevelPair{Job="RNG", Level=10}},
            {"Shadowbind", new JobAndLevelPair{Job="RNG", Level=40}},
            {"Camouflage", new JobAndLevelPair{Job="RNG", Level=20}},
            {"Sharpshot", new JobAndLevelPair{Job="RNG", Level=1}},
            {"Barrage", new JobAndLevelPair{Job="RNG", Level=30}},
            {"Call Wyvern", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Third Eye", new JobAndLevelPair{Job="SAM", Level=15}},
            {"Meditate", new JobAndLevelPair{Job="SAM", Level=30}},
            {"Warding Circle", new JobAndLevelPair{Job="SAM", Level=5}},
            {"Ancient Circle", new JobAndLevelPair{Job="DRG", Level=5}},
            {"Jump", new JobAndLevelPair{Job="DRG", Level=10}},
            {"High Jump", new JobAndLevelPair{Job="DRG", Level=35}},
            {"Super Jump", new JobAndLevelPair{Job="DRG", Level=50}},
            {"Fight", new JobAndLevelPair{Job="BST", Level=1}},
            {"Heel", new JobAndLevelPair{Job="BST", Level=10}},
            {"Leave", new JobAndLevelPair{Job="BST", Level=35}},
            {"Sic", new JobAndLevelPair{Job="BST", Level=25}},
            {"Stay", new JobAndLevelPair{Job="BST", Level=15}},
            {"Divine Seal", new JobAndLevelPair{Job="WHM", Level=15}},
            {"Elemental Seal", new JobAndLevelPair{Job="BLM", Level=15}},
            {"Trick Attack", new JobAndLevelPair{Job="THF", Level=30}},
            {"Weapon Bash", new JobAndLevelPair{Job="DRK", Level=20}},
            {"Reward", new JobAndLevelPair{Job="BST", Level=12}},
            {"Cover", new JobAndLevelPair{Job="PLD", Level=35}},
            {"Spirit Link", new JobAndLevelPair{Job="DRG", Level=25}},
            {"Enrage", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Chi Blast", new JobAndLevelPair{Job="MNK", Level=41}},
            {"Convert", new JobAndLevelPair{Job="RDM", Level=40}},
            {"Accomplice", new JobAndLevelPair{Job="THF", Level=65}},
            {"Call Beast", new JobAndLevelPair{Job="BST", Level=23}},
            {"Unlimited Shot", new JobAndLevelPair{Job="RNG", Level=51}},
            {"Dismiss", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Assault", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Retreat", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Release", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Blood Pact: Rage", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Rampart", new JobAndLevelPair{Job="PLD", Level=62}},
            {"Azure Lore", new JobAndLevelPair{Job="BLU", Level=1}},
            {"Chain Affinity", new JobAndLevelPair{Job="BLU", Level=40}},
            {"Burst Affinity", new JobAndLevelPair{Job="BLU", Level=25}},
            {"Wild Card", new JobAndLevelPair{Job="COR", Level=1}},
            {"Phantom Roll", new JobAndLevelPair{Job="COR", Level=5}},
            {"Fighter&apsts Roll", new JobAndLevelPair{Job="COR", Level=49}},
            {"Monk&apsts Roll", new JobAndLevelPair{Job="COR", Level=31}},
            {"Healer&apsts Roll", new JobAndLevelPair{Job="COR", Level=20}},
            {"Wizard&apsts Roll", new JobAndLevelPair{Job="COR", Level=58}},
            {"Warlock&apsts Roll", new JobAndLevelPair{Job="COR", Level=46}},
            {"Rogue&apsts Roll", new JobAndLevelPair{Job="COR", Level=43}},
            {"Gallant&apsts Roll", new JobAndLevelPair{Job="COR", Level=55}},
            {"Chaos Roll", new JobAndLevelPair{Job="COR", Level=14}},
            {"Beast Roll", new JobAndLevelPair{Job="COR", Level=34}},
            {"Choral Roll", new JobAndLevelPair{Job="COR", Level=26}},
            {"Hunter&apsts Roll", new JobAndLevelPair{Job="COR", Level=11}},
            {"Samurai Roll", new JobAndLevelPair{Job="COR", Level=37}},
            {"Ninja Roll", new JobAndLevelPair{Job="COR", Level=8}},
            {"Drachen Roll", new JobAndLevelPair{Job="COR", Level=23}},
            {"Evoker&apsts Roll", new JobAndLevelPair{Job="COR", Level=40}},
            {"Magus&apsts Roll", new JobAndLevelPair{Job="COR", Level=17}},
            {"Corsair&apsts Roll", new JobAndLevelPair{Job="COR", Level=5}},
            {"Puppet Roll", new JobAndLevelPair{Job="COR", Level=52}},
            {"Dancer&apsts Roll", new JobAndLevelPair{Job="COR", Level=61}},
            {"Scholar&apsts Roll", new JobAndLevelPair{Job="COR", Level=64}},
            {"Bolter&apsts Roll", new JobAndLevelPair{Job="COR", Level=76}},
            {"Caster&apsts Roll", new JobAndLevelPair{Job="COR", Level=79}},
            {"Courser&apsts Roll", new JobAndLevelPair{Job="COR", Level=81}},
            {"Blitzer&apsts Roll", new JobAndLevelPair{Job="COR", Level=83}},
            {"Tactician&apsts Roll", new JobAndLevelPair{Job="COR", Level=86}},
            {"Double-Up", new JobAndLevelPair{Job="COR", Level=5}},
            {"Quick Draw", new JobAndLevelPair{Job="COR", Level=40}},
            {"Fire Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Ice Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Wind Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Earth Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Thunder Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Water Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Light Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Dark Shot", new JobAndLevelPair{Job="COR", Level=40}},
            {"Random Deal", new JobAndLevelPair{Job="COR", Level=50}},
            {"Overdrive", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Activate", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Repair", new JobAndLevelPair{Job="PUP", Level=15}},
            {"Deploy", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Deactivate", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Retrieve", new JobAndLevelPair{Job="PUP", Level=10}},
            {"Fire Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Ice Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Wind Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Earth Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Thunder Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Water Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Light Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Dark Maneuver", new JobAndLevelPair{Job="PUP", Level=1}},
            {"Warrior&apsts Charge", new JobAndLevelPair{Job="WAR", Level=75}},
            {"Tomahawk", new JobAndLevelPair{Job="WAR", Level=75}},
            {"Mantra", new JobAndLevelPair{Job="MNK", Level=75}},
            {"Formless Strikes", new JobAndLevelPair{Job="MNK", Level=75}},
            {"Martyr", new JobAndLevelPair{Job="WHM", Level=75}},
            {"Devotion", new JobAndLevelPair{Job="WHM", Level=75}},
            {"Assassin&apsts Charge", new JobAndLevelPair{Job="THF", Level=75}},
            {"Feint", new JobAndLevelPair{Job="THF", Level=75}},
            {"Fealty", new JobAndLevelPair{Job="PLD", Level=75}},
            {"Chivalry", new JobAndLevelPair{Job="PLD", Level=75}},
            {"Dark Seal", new JobAndLevelPair{Job="DRK", Level=75}},
            {"Diabolic Eye", new JobAndLevelPair{Job="DRK", Level=75}},
            {"Feral Howl", new JobAndLevelPair{Job="BST", Level=75}},
            {"Killer Instinct", new JobAndLevelPair{Job="BST", Level=75}},
            {"Nightingale", new JobAndLevelPair{Job="BRD", Level=75}},
            {"Troubadour", new JobAndLevelPair{Job="BRD", Level=75}},
            {"Stealth Shot", new JobAndLevelPair{Job="RNG", Level=75}},
            {"Flashy Shot", new JobAndLevelPair{Job="RNG", Level=75}},
            {"Shikikoyo", new JobAndLevelPair{Job="SAM", Level=75}},
            {"Blade Bash", new JobAndLevelPair{Job="SAM", Level=75}},
            {"Deep Breathing", new JobAndLevelPair{Job="DRG", Level=75}},
            {"Angon", new JobAndLevelPair{Job="DRG", Level=75}},
            {"Sange", new JobAndLevelPair{Job="NIN", Level=75}},
            {"Blood Pact: Ward", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Hasso", new JobAndLevelPair{Job="SAM", Level=25}},
            {"Seigan", new JobAndLevelPair{Job="SAM", Level=35}},
            {"Convergence", new JobAndLevelPair{Job="BLU", Level=75}},
            {"Diffusion", new JobAndLevelPair{Job="BLU", Level=75}},
            {"Snake Eye", new JobAndLevelPair{Job="COR", Level=75}},
            {"Fold", new JobAndLevelPair{Job="COR", Level=75}},
            {"Role Reversal", new JobAndLevelPair{Job="PUP", Level=7}},
            {"Ventriloquy", new JobAndLevelPair{Job="PUP", Level=75}},
            {"Trance", new JobAndLevelPair{Job="DNC", Level=1}},
            {"Sambas", new JobAndLevelPair{Job="DNC", Level=5}},
            {"Waltzes", new JobAndLevelPair{Job="DNC", Level=15}},
            {"Drain Samba", new JobAndLevelPair{Job="DNC", Level=5}},
            {"Drain Samba II", new JobAndLevelPair{Job="DNC", Level=35}},
            {"Drain Samba III", new JobAndLevelPair{Job="DNC", Level=65}},
            {"Aspir Samba", new JobAndLevelPair{Job="DNC", Level=25}},
            {"Aspir Samba II", new JobAndLevelPair{Job="DNC", Level=60}},
            {"Haste Samba", new JobAndLevelPair{Job="DNC", Level=45}},
            {"Curing Waltz", new JobAndLevelPair{Job="DNC", Level=15}},
            {"Curing Waltz II", new JobAndLevelPair{Job="DNC", Level=30}},
            {"Curing Waltz III", new JobAndLevelPair{Job="DNC", Level=45}},
            {"Curing Waltz IV", new JobAndLevelPair{Job="DNC", Level=70}},
            {"Healing Waltz", new JobAndLevelPair{Job="DNC", Level=35}},
            {"Divine Waltz", new JobAndLevelPair{Job="DNC", Level=25}},
            {"Spectral Jig", new JobAndLevelPair{Job="DNC", Level=25}},
            {"Chocobo Jig", new JobAndLevelPair{Job="DNC", Level=55}},
            {"Jigs", new JobAndLevelPair{Job="DNC", Level=25}},
            {"Steps", new JobAndLevelPair{Job="DNC", Level=20}},
            {"Flourishes I", new JobAndLevelPair{Job="DNC", Level=20}},
            {"Quickstep", new JobAndLevelPair{Job="DNC", Level=20}},
            {"Box Step", new JobAndLevelPair{Job="DNC", Level=30}},
            {"Stutter Step", new JobAndLevelPair{Job="DNC", Level=40}},
            {"Animated Flourish", new JobAndLevelPair{Job="DNC", Level=20}},
            {"Desperate Flourish", new JobAndLevelPair{Job="DNC", Level=30}},
            {"Reverse Flourish", new JobAndLevelPair{Job="DNC", Level=40}},
            {"Violent Flourish", new JobAndLevelPair{Job="DNC", Level=45}},
            {"Building Flourish", new JobAndLevelPair{Job="DNC", Level=50}},
            {"Wild Flourish", new JobAndLevelPair{Job="DNC", Level=60}},
            {"Tabula Rasa", new JobAndLevelPair{Job="SCH", Level=1}},
            {"Light Arts", new JobAndLevelPair{Job="SCH", Level=10}},
            {"Dark Arts", new JobAndLevelPair{Job="SCH", Level=10}},
            {"Flourishes II", new JobAndLevelPair{Job="DNC", Level=40}},
            {"Modus Veritas", new JobAndLevelPair{Job="SCH", Level=65}},
            {"Penury", new JobAndLevelPair{Job="SCH", Level=10}},
            {"Celerity", new JobAndLevelPair{Job="SCH", Level=25}},
            {"Rapture", new JobAndLevelPair{Job="SCH", Level=55}},
            {"Accession", new JobAndLevelPair{Job="SCH", Level=40}},
            {"Parsimony", new JobAndLevelPair{Job="SCH", Level=10}},
            {"Alacrity", new JobAndLevelPair{Job="SCH", Level=25}},
            {"Ebullience", new JobAndLevelPair{Job="SCH", Level=55}},
            {"Manifestation", new JobAndLevelPair{Job="SCH", Level=40}},
            {"Stratagems", new JobAndLevelPair{Job="SCH", Level=10}},
            {"Velocity Shot", new JobAndLevelPair{Job="RNG", Level=45}},
            {"Snarl", new JobAndLevelPair{Job="BST", Level=45}},
            {"Retaliation", new JobAndLevelPair{Job="WAR", Level=60}},
            {"Footwork", new JobAndLevelPair{Job="MNK", Level=65}},
            {"Despoil", new JobAndLevelPair{Job="THF", Level=77}},
            {"Pianissimo", new JobAndLevelPair{Job="BRD", Level=20}},
            {"Sekkanoki", new JobAndLevelPair{Job="SAM", Level=40}},
            {"Elemental Siphon", new JobAndLevelPair{Job="SMN", Level=50}},
            {"Sublimation", new JobAndLevelPair{Job="SCH", Level=35}},
            {"Addendum: White", new JobAndLevelPair{Job="SCH", Level=10}},
            {"Addendum: Black", new JobAndLevelPair{Job="SCH", Level=30}},
            {"Collaborator", new JobAndLevelPair{Job="THF", Level=65}},
            {"Saber Dance", new JobAndLevelPair{Job="DNC", Level=75}},
            {"Fan Dance", new JobAndLevelPair{Job="DNC", Level=75}},
            {"No Foot Rise", new JobAndLevelPair{Job="DNC", Level=75}},
            {"Altruism", new JobAndLevelPair{Job="SCH", Level=75}},
            {"Focalization", new JobAndLevelPair{Job="SCH", Level=75}},
            {"Tranquility", new JobAndLevelPair{Job="SCH", Level=75}},
            {"Equanimity", new JobAndLevelPair{Job="SCH", Level=75}},
            {"Enlightenment", new JobAndLevelPair{Job="SCH", Level=75}},
            {"Afflatus Solace", new JobAndLevelPair{Job="WHM", Level=40}},
            {"Afflatus Misery", new JobAndLevelPair{Job="WHM", Level=40}},
            {"Composure", new JobAndLevelPair{Job="RDM", Level=50}},
            {"Yonin", new JobAndLevelPair{Job="NIN", Level=40}},
            {"Innin", new JobAndLevelPair{Job="NIN", Level=40}},
            {"Avatar&apsts Favor", new JobAndLevelPair{Job="SMN", Level=55}},
            {"Ready", new JobAndLevelPair{Job="BST", Level=25}},
            {"Restraint", new JobAndLevelPair{Job="WAR", Level=77}},
            {"Perfect Counter", new JobAndLevelPair{Job="MNK", Level=79}},
            {"Mana Wall", new JobAndLevelPair{Job="BLM", Level=76}},
            {"Divine Emblem", new JobAndLevelPair{Job="PLD", Level=78}},
            {"Nether Void", new JobAndLevelPair{Job="DRK", Level=78}},
            {"Double Shot", new JobAndLevelPair{Job="RNG", Level=79}},
            {"Sengikori", new JobAndLevelPair{Job="SAM", Level=77}},
            {"Futae", new JobAndLevelPair{Job="NIN", Level=77}},
            {"Spirit Jump", new JobAndLevelPair{Job="DRG", Level=77}},
            {"Presto", new JobAndLevelPair{Job="DNC", Level=77}},
            {"Divine Waltz II", new JobAndLevelPair{Job="DNC", Level=78}},
            {"Flourishes III", new JobAndLevelPair{Job="DNC", Level=80}},
            {"Climactic Flourish", new JobAndLevelPair{Job="DNC", Level=80}},
            {"Libra", new JobAndLevelPair{Job="SCH", Level=76}},
            {"Tactical Switch", new JobAndLevelPair{Job="PUP", Level=79}},
            {"Blood Rage", new JobAndLevelPair{Job="WAR", Level=87}},
            {"Impetus", new JobAndLevelPair{Job="MNK", Level=88}},
            {"Divine Caress", new JobAndLevelPair{Job="WHM", Level=83}},
            {"Sacrosanctity", new JobAndLevelPair{Job="WHM", Level=95}},
            {"Enmity Douse", new JobAndLevelPair{Job="BLM", Level=87}},
            {"Manawell", new JobAndLevelPair{Job="BLM", Level=95}},
            {"Saboteur", new JobAndLevelPair{Job="RDM", Level=83}},
            {"Spontaneity", new JobAndLevelPair{Job="RDM", Level=95}},
            {"Conspirator", new JobAndLevelPair{Job="THF", Level=87}},
            {"Sepulcher", new JobAndLevelPair{Job="PLD", Level=87}},
            {"Palisade", new JobAndLevelPair{Job="PLD", Level=95}},
            {"Arcane Crest", new JobAndLevelPair{Job="DRK", Level=87}},
            {"Scarlet Delirium", new JobAndLevelPair{Job="DRK", Level=95}},
            {"Spur", new JobAndLevelPair{Job="BST", Level=83}},
            {"Run Wild", new JobAndLevelPair{Job="BST", Level=93}},
            {"Tenuto", new JobAndLevelPair{Job="BRD", Level=83}},
            {"Marcato", new JobAndLevelPair{Job="BRD", Level=95}},
            {"Bounty Shot", new JobAndLevelPair{Job="RNG", Level=87}},
            {"Decoy Shot", new JobAndLevelPair{Job="RNG", Level=95}},
            {"Hamanoha", new JobAndLevelPair{Job="SAM", Level=87}},
            {"Hagakure", new JobAndLevelPair{Job="SAM", Level=95}},
            {"Issekigan", new JobAndLevelPair{Job="NIN", Level=95}},
            {"Dragon Breaker", new JobAndLevelPair{Job="DRG", Level=87}},
            {"Soul Jump", new JobAndLevelPair{Job="DRG", Level=85}},
            {"Steady Wing", new JobAndLevelPair{Job="DRG", Level=95}},
            {"Mana Cede", new JobAndLevelPair{Job="SMN", Level=87}},
            {"Efflux", new JobAndLevelPair{Job="BLU", Level=83}},
            {"Unbridled Learning", new JobAndLevelPair{Job="BLU", Level=95}},
            {"Triple Shot", new JobAndLevelPair{Job="COR", Level=87}},
            {"Allies&apst Roll", new JobAndLevelPair{Job="COR", Level=89}},
            {"Miser&apsts Roll", new JobAndLevelPair{Job="COR", Level=92}},
            {"Companion&apsts Roll", new JobAndLevelPair{Job="COR", Level=95}},
            {"Avenger&apsts Roll", new JobAndLevelPair{Job="COR", Level=97}},
            {"Cooldown", new JobAndLevelPair{Job="PUP", Level=95}},
            {"Deus Ex Automata", new JobAndLevelPair{Job="PUP", Level=5}},
            {"Curing Waltz V", new JobAndLevelPair{Job="DNC", Level=100}},
            {"Feather Step", new JobAndLevelPair{Job="DNC", Level=83}},
            {"Striking Flourish", new JobAndLevelPair{Job="DNC", Level=100}},
            {"Ternary Flourish", new JobAndLevelPair{Job="DNC", Level=100}},
            {"Perpetuance", new JobAndLevelPair{Job="SCH", Level=87}},
            {"Immanence", new JobAndLevelPair{Job="SCH", Level=87}},
            {"Smiting Breath", new JobAndLevelPair{Job="DRG", Level=90}},
            {"Restoring Breath", new JobAndLevelPair{Job="DRG", Level=90}},
            {"Konzen-ittai", new JobAndLevelPair{Job="SAM", Level=65}},
            {"Bully", new JobAndLevelPair{Job="THF", Level=93}},
            {"Maintenance", new JobAndLevelPair{Job="PUP", Level=30}},
            {"Brazen Rush", new JobAndLevelPair{Job="WAR", Level=96}},
            {"Inner Strength", new JobAndLevelPair{Job="MNK", Level=96}},
            {"Asylum", new JobAndLevelPair{Job="WHM", Level=96}},
            {"Subtle Sorcery", new JobAndLevelPair{Job="BLM", Level=96}},
            {"Stymie", new JobAndLevelPair{Job="RDM", Level=96}},
            {"Larceny", new JobAndLevelPair{Job="THF", Level=96}},
            {"Intervene", new JobAndLevelPair{Job="PLD", Level=96}},
            {"Soul Enslavement", new JobAndLevelPair{Job="DRK", Level=96}},
            {"Unleash", new JobAndLevelPair{Job="BST", Level=96}},
            {"Clarion Call", new JobAndLevelPair{Job="BRD", Level=96}},
            {"Overkill", new JobAndLevelPair{Job="RNG", Level=96}},
            {"Yaegasumi", new JobAndLevelPair{Job="SAM", Level=96}},
            {"Mikage", new JobAndLevelPair{Job="NIN", Level=96}},
            {"Fly High", new JobAndLevelPair{Job="DRG", Level=96}},
            {"Astral Conduit", new JobAndLevelPair{Job="SMN", Level=96}},
            {"Unbridled Wisdom", new JobAndLevelPair{Job="BLU", Level=96}},
            {"Cutting Cards", new JobAndLevelPair{Job="COR", Level=96}},
            {"Heady Artifice", new JobAndLevelPair{Job="PUP", Level=96}},
            {"Grand Pas", new JobAndLevelPair{Job="DNC", Level=96}},
            {"Caper Emissarius", new JobAndLevelPair{Job="SCH", Level=96}},
            {"Bolster", new JobAndLevelPair{Job="GEO", Level=1}},
            {"Swipe", new JobAndLevelPair{Job="RUN", Level=25}},
            {"Full Circle", new JobAndLevelPair{Job="GEO", Level=5}},
            {"Lasting Emanation", new JobAndLevelPair{Job="GEO", Level=25}},
            {"Ecliptic Attrition", new JobAndLevelPair{Job="GEO", Level=25}},
            {"Collimated Fervor", new JobAndLevelPair{Job="GEO", Level=40}},
            {"Life Cycle", new JobAndLevelPair{Job="GEO", Level=50}},
            {"Blaze of Glory", new JobAndLevelPair{Job="GEO", Level=60}},
            {"Dematerialize", new JobAndLevelPair{Job="GEO", Level=70}},
            {"Theurgic Focus", new JobAndLevelPair{Job="GEO", Level=80}},
            {"Concentric Pulse", new JobAndLevelPair{Job="GEO", Level=90}},
            {"Mending Halation", new JobAndLevelPair{Job="GEO", Level=75}},
            {"Radial Arcana", new JobAndLevelPair{Job="GEO", Level=75}},
            {"Elemental Sforzo", new JobAndLevelPair{Job="RUN", Level=1}},
            {"Rune Enchantment", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Ignis", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Gelus", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Flabra", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Tellus", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Sulpor", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Unda", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Lux", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Tenebrae", new JobAndLevelPair{Job="RUN", Level=5}},
            {"Vallation", new JobAndLevelPair{Job="RUN", Level=10}},
            {"Swordplay", new JobAndLevelPair{Job="RUN", Level=20}},
            {"Lunge", new JobAndLevelPair{Job="RUN", Level=25}},
            {"Pflug", new JobAndLevelPair{Job="RUN", Level=40}},
            {"Embolden", new JobAndLevelPair{Job="RUN", Level=60}},
            {"Valiance", new JobAndLevelPair{Job="RUN", Level=50}},
            {"Gambit", new JobAndLevelPair{Job="RUN", Level=70}},
            {"Liement", new JobAndLevelPair{Job="RUN", Level=85}},
            {"One for All", new JobAndLevelPair{Job="RUN", Level=95}},
            {"Rayke", new JobAndLevelPair{Job="RUN", Level=75}},
            {"Battuta", new JobAndLevelPair{Job="RUN", Level=75}},
            {"Widened Compass", new JobAndLevelPair{Job="GEO", Level=96}},
            {"Odyllic Subterfuge", new JobAndLevelPair{Job="RUN", Level=96}},
            {"Ward", new JobAndLevelPair{Job="RUN", Level=10}},
            {"Effusion", new JobAndLevelPair{Job="RUN", Level=25}},
            {"Chocobo Jig II", new JobAndLevelPair{Job="DNC", Level=100}},
            {"Relinquish", new JobAndLevelPair{Job="MON", Level=1}},
            {"Vivacious Pulse", new JobAndLevelPair{Job="RUN", Level=65}},
            {"Contradance", new JobAndLevelPair{Job="DNC", Level=50}},
            {"Apogee", new JobAndLevelPair{Job="SMN", Level=50}},
            {"Entrust", new JobAndLevelPair{Job="GEO", Level=75}},
            {"Bestial Loyalty", new JobAndLevelPair{Job="BST", Level=23}},
            {"Healing Ruby", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Poison Nails", new JobAndLevelPair{Job="SMN", Level=5}},
            {"Shining Ruby", new JobAndLevelPair{Job="SMN", Level=24}},
            {"Glittering Ruby", new JobAndLevelPair{Job="SMN", Level=44}},
            {"Meteorite", new JobAndLevelPair{Job="SMN", Level=55}},
            {"Healing Ruby II", new JobAndLevelPair{Job="SMN", Level=65}},
            {"Searing Light", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Holy Mist", new JobAndLevelPair{Job="SMN", Level=76}},
            {"Soothing Ruby", new JobAndLevelPair{Job="SMN", Level=94}},
            {"Regal Scratch", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Mewing Lullaby", new JobAndLevelPair{Job="SMN", Level=25}},
            {"Eerie Eye", new JobAndLevelPair{Job="SMN", Level=55}},
            {"Level ? Holy", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Raise II", new JobAndLevelPair{Job="SMN", Level=15}},
            {"Reraise II", new JobAndLevelPair{Job="SMN", Level=30}},
            {"Altana&apsts Favor", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Moonlit Charge", new JobAndLevelPair{Job="SMN", Level=5}},
            {"Crescent Fang", new JobAndLevelPair{Job="SMN", Level=10}},
            {"Lunar Cry", new JobAndLevelPair{Job="SMN", Level=21}},
            {"Lunar Roar", new JobAndLevelPair{Job="SMN", Level=32}},
            {"Ecliptic Growl", new JobAndLevelPair{Job="SMN", Level=43}},
            {"Ecliptic Howl", new JobAndLevelPair{Job="SMN", Level=54}},
            {"Eclipse Bite", new JobAndLevelPair{Job="SMN", Level=65}},
            {"Howling Moon", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Lunar Bay", new JobAndLevelPair{Job="SMN", Level=78}},
            {"Heavenward Howl", new JobAndLevelPair{Job="SMN", Level=96}},
            {"Punch", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Fire II", new JobAndLevelPair{Job="SMN", Level=10}},
            {"Burning Strike", new JobAndLevelPair{Job="SMN", Level=23}},
            {"Double Punch", new JobAndLevelPair{Job="SMN", Level=30}},
            {"Crimson Howl", new JobAndLevelPair{Job="SMN", Level=38}},
            {"Fire IV", new JobAndLevelPair{Job="SMN", Level=60}},
            {"Flaming Crush", new JobAndLevelPair{Job="SMN", Level=70}},
            {"Meteor Strike", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Inferno", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Inferno Howl", new JobAndLevelPair{Job="SMN", Level=88}},
            {"Conflag Strike", new JobAndLevelPair{Job="SMN", Level=100}},
            {"Rock Throw", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Stone II", new JobAndLevelPair{Job="SMN", Level=10}},
            {"Rock Buster", new JobAndLevelPair{Job="SMN", Level=21}},
            {"Megalith Throw", new JobAndLevelPair{Job="SMN", Level=35}},
            {"Earthen Ward", new JobAndLevelPair{Job="SMN", Level=46}},
            {"Stone IV", new JobAndLevelPair{Job="SMN", Level=60}},
            {"Mountain Buster", new JobAndLevelPair{Job="SMN", Level=70}},
            {"Geocrush", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Earthen Fury", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Earthen Armor", new JobAndLevelPair{Job="SMN", Level=82}},
            {"Crag Throw", new JobAndLevelPair{Job="SMN", Level=100}},
            {"Barracuda Dive", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Water II", new JobAndLevelPair{Job="SMN", Level=10}},
            {"Tail Whip", new JobAndLevelPair{Job="SMN", Level=26}},
            {"Spring Water", new JobAndLevelPair{Job="SMN", Level=47}},
            {"Slowga", new JobAndLevelPair{Job="SMN", Level=33}},
            {"Water IV", new JobAndLevelPair{Job="SMN", Level=60}},
            {"Spinning Dive", new JobAndLevelPair{Job="SMN", Level=70}},
            {"Grand Fall", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Tidal Wave", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Tidal Roar", new JobAndLevelPair{Job="SMN", Level=84}},
            {"Soothing Current", new JobAndLevelPair{Job="SMN", Level=100}},
            {"Claw", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Aero II", new JobAndLevelPair{Job="SMN", Level=10}},
            {"Whispering Wind", new JobAndLevelPair{Job="SMN", Level=36}},
            {"Hastega", new JobAndLevelPair{Job="SMN", Level=48}},
            {"Aerial Armor", new JobAndLevelPair{Job="SMN", Level=25}},
            {"Aero IV", new JobAndLevelPair{Job="SMN", Level=60}},
            {"Predator Claws", new JobAndLevelPair{Job="SMN", Level=70}},
            {"Wind Blade", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Aerial Blast", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Fleet Wind", new JobAndLevelPair{Job="SMN", Level=86}},
            {"Hastega II", new JobAndLevelPair{Job="SMN", Level=100}},
            {"Axe Kick", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Blizzard II", new JobAndLevelPair{Job="SMN", Level=10}},
            {"Frost Armor", new JobAndLevelPair{Job="SMN", Level=28}},
            {"Sleepga", new JobAndLevelPair{Job="SMN", Level=39}},
            {"Double Slap", new JobAndLevelPair{Job="SMN", Level=50}},
            {"Blizzard IV", new JobAndLevelPair{Job="SMN", Level=60}},
            {"Rush", new JobAndLevelPair{Job="SMN", Level=70}},
            {"Heavenly Strike", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Diamond Dust", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Diamond Storm", new JobAndLevelPair{Job="SMN", Level=90}},
            {"Crystal Blessing", new JobAndLevelPair{Job="SMN", Level=100}},
            {"Shock Strike", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Thunder II", new JobAndLevelPair{Job="SMN", Level=10}},
            {"Rolling Thunder", new JobAndLevelPair{Job="SMN", Level=31}},
            {"Thunderspark", new JobAndLevelPair{Job="SMN", Level=19}},
            {"Lightning Armor", new JobAndLevelPair{Job="SMN", Level=42}},
            {"Thunder IV", new JobAndLevelPair{Job="SMN", Level=60}},
            {"Chaotic Strike", new JobAndLevelPair{Job="SMN", Level=70}},
            {"Thunderstorm", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Judgment Bolt", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Shock Squall", new JobAndLevelPair{Job="SMN", Level=92}},
            {"Volt Strike", new JobAndLevelPair{Job="SMN", Level=100}},
            {"Healing Breath IV", new JobAndLevelPair{Job="DRG", Level=80}},
            {"Healing Breath", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Healing Breath II", new JobAndLevelPair{Job="DRG", Level=20}},
            {"Healing Breath III", new JobAndLevelPair{Job="DRG", Level=40}},
            {"Remove Poison", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Remove Blindness", new JobAndLevelPair{Job="DRG", Level=20}},
            {"Remove Paralysis", new JobAndLevelPair{Job="DRG", Level=40}},
            {"Flame Breath", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Frost Breath", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Gust Breath", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Sand Breath", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Lightning Breath", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Hydro Breath", new JobAndLevelPair{Job="DRG", Level=1}},
            {"Super Climb", new JobAndLevelPair{Job="DRG", Level=50}},
            {"Remove Curse", new JobAndLevelPair{Job="DRG", Level=100}},
            {"Remove Disease", new JobAndLevelPair{Job="DRG", Level=100}},
            {"Camisado", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Somnolence", new JobAndLevelPair{Job="SMN", Level=20}},
            {"Nightmare", new JobAndLevelPair{Job="SMN", Level=29}},
            {"Ultimate Terror", new JobAndLevelPair{Job="SMN", Level=37}},
            {"Noctoshield", new JobAndLevelPair{Job="SMN", Level=49}},
            {"Dream Shroud", new JobAndLevelPair{Job="SMN", Level=56}},
            {"Nether Blast", new JobAndLevelPair{Job="SMN", Level=65}},
            {"Cacodemonia", new JobAndLevelPair{Job="SMN", Level=100}},
            {"Ruinous Omen", new JobAndLevelPair{Job="SMN", Level=1}},
            {"Night Terror", new JobAndLevelPair{Job="SMN", Level=80}},
            {"Pavor Nocturnus", new JobAndLevelPair{Job="SMN", Level=98}},
            {"Deconstruction", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Chronoshift", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Zantetsuken", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Perfect Defense", new JobAndLevelPair{Job="SMN", Level=75}},
            {"Foot Kick", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Dust Cloud", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Whirl Claws", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Head Butt", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Dream Flower", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Wild Oats", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Leaf Dagger", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Scream", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Roar", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Razor Fang", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Claw Cyclone", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Tail Blow", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Fireball", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Blockhead", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Brain Crush", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Infrasonics", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Secretion", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Lamb Chop", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Rage", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Sheep Charge", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Sheep Song", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Bubble Shower", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Bubble Curtain", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Big Scissors", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Scissor Guard", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Metallic Body", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Needleshot", new JobAndLevelPair{Job="UNK", Level=1}},
            {"1000 Needles", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Frogkick", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Spore", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Queasyshroom", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Numbshroom", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Shakeshroom", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Silence Gas", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Dark Spore", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Power Attack", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Hi-Freq Field", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Rhino Attack", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Rhino Guard", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Spoil", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Cursed Sphere", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Venom", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Sandblast", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Sandpit", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Venom Spray", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Mandibular Bite", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Soporific", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Gloeosuccus", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Palsy Pollen", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Geist Wall", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Numbing Noise", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Nimble Snap", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Cyclotail", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Toxic Spit", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Double Claw", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Grapple", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Spinning Top", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Filamented Hold", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Chaotic Eye", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Blaster", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Suction", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Drainkiss", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Snow Cloud", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Wild Carrot", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Sudden Lunge", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Spiral Spin", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Noisome Powder", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Acid Mist", new JobAndLevelPair{Job="UNK", Level=1}},
            {"TP Drainkiss", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Scythe Tail", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Ripper Fang", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Chomp Rush", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Charged Whisker", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Purulent Ooze", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Corrosive Ooze", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Back Heel", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Jettatura", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Choke Breath", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Fantod", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Tortoise Stomp", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Harden Shell", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Aqua Breath", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Wing Slap", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Beak Lunge", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Intimidate", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Recoil Dive", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Water Wall", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Sensilla Blades", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Tegmina Buffet", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Molting Plumage", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Swooping Frenzy", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Sweeping Gouge", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Zealous Snort", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Pentapeck", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Tickling Tendrils", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Stink Bomb", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Nectarous Deluge", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Nepenthic Plunge", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Somersault ", new JobAndLevelPair{Job="UNK", Level=1}},
            {"Pacifying Ruby", new JobAndLevelPair{Job="UNK", Level=1}}
        };
    }
}

